name: Build and Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image to ECR
      run: |
        IMAGE_URI=${{ secrets.ECR_REPOSITORY }}:latest
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI

    # Optional: Deploy to EC2 via SSH
    
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.EC2_KEY }}" > ~/.ssh/my-key.pem
        chmod 600 ~/.ssh/my-key.pem

    - name: Deploy to EC2
      if: ${{ secrets.EC2_HOST }}
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "deploy_script.sh"
        target: "~/"

    - name: Run deploy script on EC2
      if: ${{ secrets.EC2_HOST }}
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          bash ~/deploy_script.sh
