name: Terraform Destroy

on:
    # Defines the trigger for the workflow
    # It will enable running the workflow manually from the GitHub Actions UI
    workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    
    env:
      
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ca-central-1 
      TERRAFORM_VER: 1.7.5     

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VER }} 

      - name: Terraform Init
        
        run: terraform init

      - name: Terraform Destroy
        
        run: terraform destroy -auto-approve
